var plural_options = {
  'ach': 'Acholi',
  'af': 'Afrikaans',
  'ak': 'Akan',
  'am': 'Amharic',
  'an': 'Aragonese',
  'ar': 'Arabic notes',
  'arn': 'Mapudungun',
  'ast': 'Asturian',
  'ay': 'Aymara',
  'az': 'Azerbaijani',

  'be': 'Belarusian',
  'bg': 'Bulgarian',
  'bn': 'Bengali',
  'bo': 'Tibetan',
  'br': 'Breton',
  'bs': 'Bosnian',

  'ca': 'Catalan',
  'cgg': 'Chiga',
  'cs': 'Czech',
  'csb': 'Kashubian',
  'cy': 'Welsh',

  'da': 'Danish',
  'de': 'German',
  'dz': 'Dzongkha',

  'el': 'Greek',
  'en': 'English',
  'eo': 'Esperanto',
  'es': 'Spanish',
  'es-ar': 'Argentinean Spanish',
  'et': 'Estonian',
  'eu': 'Basque',

  'fa': 'Persian',
  'fi': 'Finnish',
  'fil': 'Filipino',
  'fo': 'Faroese',
  'fr': 'French',
  'fur': 'Friulian',
  'fy': 'Frisian',

  'ga': 'Irish',
  'gl': 'Galician',
  'gu': 'Gujarati',
  'gun': 'Gun',

  'ha': 'Hausa',
  'he': 'Hebrew',
  'hi': 'Hindi',
  'hy': 'Armenian',
  'hr': 'Croatian',
  'hu': 'Hungarian',

  'ia': 'Interlingua',
  'id': 'Indonesian',
  'is': 'Icelandic',
  'it': 'Italian',

  'ja': 'Japanese',
  'jv': 'Javanese',

  'ka': 'Georgian',
  'kk': 'Kazakh',
  'km': 'Khmer',
  'kn': 'Kannada',
  'ko': 'Korean',
  'ku': 'Kurdish',
  'kw': 'Cornish',
  'ky': 'Kyrgyz',

  'lb': 'Letzeburgesch',
  'ln': 'Lingala',
  'lo': 'Lao',
  'lt': 'Lithuanian',
  'lv': 'Latvian',

  'mfe': 'Mauritian Creole',
  'mg': 'Malagasy',
  'mi': 'Maori',
  'mk': 'Macedonian',
  'ml': 'Malayalam',
  'mn': 'Mongolian',
  'mr': 'Marathi',
  'ms': 'Malay',
  'mt': 'Maltese',

  'nah': 'Nahuatl',
  'nap': 'Neapolitan',
  'nb': 'Norwegian Bokmal',
  'ne': 'Nepali',
  'nl': 'Dutch',
  'se': 'Northern Sami',
  'nn': 'Norwegian Nynorsk',
  'no': 'Norwegian (old code)',
  'nso': 'Northern Sotho',

  'oc': 'Occitan',
  'or': 'Oriya',

  'ps': 'Pashto',
  'pa': 'Punjabi',
  'pap': 'Papiamento',
  'pl': 'Polish',
  'pms': 'Piemontese',
  'pt': 'Portuguese',
  'pt-br': 'Brazilian Portuguese',

  'rm': 'Romansh',
  'ro': 'Romanian',
  'ru': 'Russian',

  'sco': 'Scots',
  'si': 'Sinhala',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'so': 'Somali',
  'son': 'Songhay',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'su': 'Sundanese',
  'sw': 'Swahili',
  'sv': 'Swedish',

  'ta': 'Tamil',
  'te': 'Telugu',
  'tg': 'Tajik',
  'ti': 'Tigrinya',
  'th': 'Thai',
  'tk': 'Turkmen',
  'tr': 'Turkish',
  'tt': 'Tatar',

  'ug': 'Uyghur',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'uz': 'Uzbek',

  'vi': 'Vietnamese',

  'wa': 'Walloon',

  'zh': 'Chinese',
  'zh-personal': 'Chinese (personal pronoun)',
};
